name: Tiers-Placeholders
version: '1.1.1'
main: xyz.matumaka.tiers.TiersPlaceholders
api-version: '1.21'
website: https://github.com/MatuMaKa/tiers-placeholders
authors: [ MatuMaKa ]
description: Puts tiers placeholders in the game. (Subtiers, McTiers, PvPTiers)
depend: [ PlaceholderAPI ]